// Package views is automatically generated by SUNPLATE toolkit.
// Please, do not edit it manually.
package views

// Context is a map[string]string of all files found in
// "./testdata/assets/views".
// It is not a []string to make easy check of whether certain
// files exist possible.
var Context = map[string]string{
	"testdata/views/test1.template": "testdata/views/test1.template",
	"testdata/views/test2.template": "testdata/views/test2.template",
}
